project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - blog.qmd
      - projects.qmd
      - gallery.qmd
      

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true

editor: visual

